// <auto-generated />
using FlashCards.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlashCards.Migrations
{
    [DbContext(typeof(FlashCardsSqlLiteDbCtx))]
    partial class FlashCardsSqlLiteDbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("FlashCards.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decks_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("FlashCards.Models.Deck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_ID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("FlashCards.Models.FlashCardStats", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Correct")
                        .HasColumnType("TEXT");

                    b.Property<int>("Decks_ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InCorrect")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPct")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("StatsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
